/*
 * This source file was generated by the Gradle 'init' task
 */
package no3;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void checkInput(int day, int month, int year) {
        
        if (year < 2500 || year > 2565) {
            System.out.println("wrong values");
            return;
        }
        
        
        if (month < 1 || month > 12) {
            System.out.println("wrong values");
            return;
        }
        
        
        if (day < 1 || day > getDaysInMonth(month)) {
            System.out.println("wrong values");
            return;
        }
        
       
        System.out.println("Correct!");
    }
    
    // ฟังก์ชันคืนค่าจำนวนวันที่ในแต่ละเดือน
    public static int getDaysInMonth(int month) {
        switch (month) {
            case 2: // กุมภาพันธ์
                    return 28; // ปีปกติ
            case 1: // มกราคม 
            case 3: // มีนาคม
            case 5: // พฤษภาคม
            case 7: // กรกฎาคม 
            case 8: // สิงหาคม
            case 10: // ตุลาคม
            case 12: // ธันวาคม
                return 31;
            case 4: // เมษายน
            case 6: // มิถุนายน
            case 9: // กันยายน
            case 11: // พฤศจิกายน
                return 30;
            default:
                return 0; // คืนค่าผิดพลาด หากเดือนไม่ถูกต้อง
        }
    }

        public static void main(String[] args) {
            Scanner sc = new Scanner(System.in);
            while (true) {
                System.out.print("Enter day: ");
                int day = sc.nextInt();
                System.out.print("Enter month: ");
                int month = sc.nextInt();
                System.out.print("Enter year: ");
                int year = sc.nextInt();
    
                checkInput(day, month, year);
    
                // ถ้าค่าถูกต้องแล้วให้หยุดการวนลูป
                if (year >= 2500 && year <= 2565 && month >= 1 && month <= 12 && day >= 1 && day <= getDaysInMonth(month)) {
                    break;
                }
            }
            sc.close();
        }

    }
