/*
 * This source file was generated by the Gradle 'init' task
 */
package no4;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public class PrimeExample2 {
        public static boolean isPrime(int n) {

            for (int i = 2; i <= Math.sqrt(n); i++) {
                if (n % i == 0) {
                    return false; 
                }
            }
            
            return true; 
        }

        public static void main(String[] args) {
            Scanner sc = new Scanner(System.in);
            System.out.print("Enter input number: ");
            int n = sc.nextInt();
            System.out.println("Prime number is ");
        
        for (int i = 1; i <= n; i++) {
            if (isPrime(i)) {
                System.out.print(i + " ");
            }
        }
        sc.close();
        }
    }
}
